---
sudo: required
dist: trusty

language: python
python: "2.7"

env:
  - ANSIBLE_VERSION=latest
  - ANSIBLE_VERSION=2.4.3.0
  - ANSIBLE_VERSION=2.4.2.0
  - ANSIBLE_VERSION=2.4.1.0
  - ANSIBLE_VERSION=2.4.0.0
  - ANSIBLE_VERSION=2.3.3.0
  - ANSIBLE_VERSION=2.3.2.0
  - ANSIBLE_VERSION=2.3.1.0
  - ANSIBLE_VERSION=2.3.0.0
  - ANSIBLE_VERSION=2.2.3.0
  - ANSIBLE_VERSION=2.2.2.0
  - ANSIBLE_VERSION=2.2.1.0
  - ANSIBLE_VERSION=2.2.0.0
  - ANSIBLE_VERSION=2.1.6
  - ANSIBLE_VERSION=2.1.5
  - ANSIBLE_VERSION=2.1.4
  - ANSIBLE_VERSION=2.1.3
  - ANSIBLE_VERSION=2.1.2
  - ANSIBLE_VERSION=2.1.1.0
  - ANSIBLE_VERSION=2.1.0.0
  - ANSIBLE_VERSION=2.0.2.0
  - ANSIBLE_VERSION=2.0.1.0
  - ANSIBLE_VERSION=2.0.0.2
  - ANSIBLE_VERSION=2.0.0.1
  - ANSIBLE_VERSION=2.0.0.0

branches:
  only:
    - master

before_install:
  - sudo apt-get update -qq

install:
  # Install Ansible.
  - if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install ansible; else pip install ansible==$ANSIBLE_VERSION; fi
  - if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install ansible-lint; fi

script:
  # Check the role/playbook's syntax.
  - ansible-playbook -i tests/inventory tests/test.yml --syntax-check

  # Run the role/playbook with ansible-playbook.
  - ansible-playbook -i tests/inventory tests/test.yml -vvvv --diff

  # Run the role/playbook again, checking to make sure it's idempotent.
  - >
    ansible-playbook -i tests/inventory tests/test.yml
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)

  - if [ "$ANSIBLE_VERSION" = "latest" ]; then ansible-lint tests/test.yml || true; fi

notifications:
  email: false
  hipchat:
    rooms:
      secure: ATB7pOOYjfsPaCfpZEbkmPDdX0Me0fy4ORCBe6bPdu5l7IlohXKRGm52fxU74tlQ5SBviwChz4gTcVkNiCY4i21ZLG6dmj8feBpNq+WFIvJmZyvmp0eqIPuTgskxOu3TKzTTyJXRhSZFOB0Kikl3OmEGx0g2DTf74kcl3LTRfZGYDzGUlyaM5HGeXZRVxDjAQnlNQiqjgKaD6B78mh0/BCHQmi5Ue+GyQSVtXdzNkoKeitdaukwqNjJCEyNtKjMRjPB6R0gY1lRADjTUe5lWvWO7HT+4e7n9pSlk30aQTnicWJJO7fq0ZKTcOY30eyA/hvHDxoJtW+24TX806WTM9XtiiBxv+PBfBKLIZyzhxBQWdVZgF+77PeMLqwnwe+kbDawaBQosrz/8vZ6kuI2UX2b43sI4ag1T8Lur/ddbGoQNLHIvlFH/QxMOZtBM0W2IQhtz9aKO6Z/pZURWxN6ebqgf6LsP01DQBCRR8rMs7GI++f8Eu4NQtzBROWnvRsOuQ2BtUQe5QL7dgfrFRfZZfjfJODrgOCkiANl9l5VglHV0RojScRP79JccZ+JM9uVEmqGDkBfTjSIm9e9Gcm9PC/gfxiXq0Wh16WSzYvvqhYIzCRnrakp6Tyy90BzW6W6QQRirsxvzPSLc7Wic1oKahZlme2cUzmE6Pd/j8xH5VwM=
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
