---
- name: Converge
  hosts: all
  become: true
  roles:
    - role: ../../../
      when: >
        false
        or (ansible_facts['distribution'] == 'Debian' and ansible_facts['distribution_major_version'] is version('10', '>='))
        or (ansible_facts['distribution'] == 'Ubuntu' and ansible_facts['distribution_major_version'] is version('18', '>='))
